version: '3.8'
services:
  web:
    image: tillu018/sit737-2025-prac4c
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
