apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongo-username: appuser
  mongo-password: S3cur3P@ss
  mongo-uri:    mongodb://appuser:S3cur3P%40ss@mongodb-service:27017/calculator?authSource=admin
